using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Achievement error codes.
    /// </summary>
    /// <remarks>
    /// These describe what the achievement configuration itself refused — currently the
    /// delete vetoes that keep referenced achievements from leaving dangling configuration
    /// behind in ladders and challenges.
    /// </remarks>
    public enum AchievementExceptionErrorCode
    {
        /// <summary>
        /// Set when we try to delete an achievement that a ladder still references
        /// through a scoring entry or a level requirement.
        /// </summary>
        [Name("Achievement referenced by ladder", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REFERENCED_BY_LADDER_NAME))]
        [ExtendedDescription("Cannot delete the achievement because a ladder references it", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REFERENCED_BY_LADDER_DESCRIPTION))]
        ReferencedByLadder = 0,

        /// <summary>
        /// Set when we try to delete an achievement that a challenge still references
        /// through a requirement.
        /// </summary>
        [Name("Achievement referenced by challenge", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REFERENCED_BY_CHALLENGE_NAME))]
        [ExtendedDescription("Cannot delete the achievement because a challenge references it", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REFERENCED_BY_CHALLENGE_DESCRIPTION))]
        ReferencedByChallenge = 1,
    }
}
