using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Achievement reward error codes.
    /// </summary>
    /// <remarks>
    /// These describe what the reward row itself refused. A failure of the handover — no stock,
    /// no register, a disabled user — keeps the error code of the subsystem that refused it, so
    /// the operator is told the actual reason rather than that the reward could not be given.
    /// </remarks>
    public enum AchievementRewardExceptionErrorCode
    {
        /// <summary>
        /// Set when we try to claim or decline a reward that has already reached a terminal status.
        /// </summary>
        [Name("Reward already processed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REWARD_ALREADY_PROCESSED_NAME))]
        [ExtendedDescription("Cannot perform the action because the reward is already processed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REWARD_ALREADY_PROCESSED_DESCRIPTION))]
        AlreadyProcessed = 0,

        /// <summary>
        /// Set when we try to re-offer a reward that was not declined.
        /// </summary>
        [Name("Reward not declined", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REWARD_NOT_DECLINED_NAME))]
        [ExtendedDescription("Only a declined reward can be re-offered", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REWARD_NOT_DECLINED_DESCRIPTION))]
        NotDeclined = 1,

        /// <summary>
        /// Set when the reward's kind has no way of being handed over at all.
        /// </summary>
        [Name("Reward not deliverable", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REWARD_NOT_DELIVERABLE_NAME))]
        [ExtendedDescription("Cannot perform the action because the reward kind has no delivery mechanism", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_ACHIEVEMENT_REWARD_NOT_DELIVERABLE_DESCRIPTION))]
        NotDeliverable = 2,
    }
}
