using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    public enum CartErrorCode
    {
        /// <summary>
        /// Specified cart id is invalid.
        /// </summary>
        [Name("Invalid cart", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ID_NAME))]
        [ExtendedDescription("The cart is invalid or expired", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_DESCRIPTION))]
        InvalidCartId = 0,

        /// <summary>
        /// Action is not supported.
        /// </summary>
        [Name("Not supported", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_NAME))]
        [ExtendedDescription("Cart action is not supported", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_DESCRIPTION))]
        NotSupported = 1,
    }
}
