using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    public enum CartErrorCode
    {
        /// <summary>
        /// Specified cart id is invalid.
        /// </summary>
        [Name("Invalid cart", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ID_NAME))]
        [ExtendedDescription("The cart is invalid or expired", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_DESCRIPTION))]
        InvalidCartId = 0,

        [Name("Invalid cart entry id", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ENTRY_ID_NAME))]
        [ExtendedDescription("The cart entry id specified is invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ENTRY_ID_DESCRIPTION))]
        InvalidCartEntryId = 1,

        /// <summary>
        /// Action is not supported.
        /// </summary>
        [Name("Not supported", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_NAME))]
        [ExtendedDescription("Cart action is not supported", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_DESCRIPTION))]
        NotSupported = 2,

        [Name("Time restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_TIME_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by time or date", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_TIME_RESTRICTED_DESCRIPTION))]
        TimeRestricted = 3,

        [Name("User group restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_USER_GROUP_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by user group", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_USER_GROUP_RESTRICTED_DESCRIPTION))]
        UserGroupRestricted = 4,

        [Name("Branch restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_BRANCH_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by branch", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_BRANCH_RESTRICTED_DESCRIPTION))]
        BranchRestricted = 5,

        [Name("Age restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_AGE_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by age", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_WAITING_LINE_AGE_RESTRICTED_DESCRIPTION))]
        AgeRestricted = 6,

        [Name("Payment exceed total", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_PAYMENT_EXCEED_TOTAL_NAME))]
        [ExtendedDescription("The payment amount exceeds the required total", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_PAYMENT_EXCEED_TOTAL_DESCRIPTION))]
        PaymentExceedTotal = 7,

        [Name("Out of stock", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_OUT_OF_STOCK_NAME))]
        [ExtendedDescription("The product is out of stock", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_OUT_OF_STOCK_DESCRIPTION))]
        OutOfStock = 8,

        [Name("Requires mark", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_REQUIRES_MARK_NAME))]
        [ExtendedDescription("The product purchase requires mark", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_REQUIRES_MARK_DESCRIPTION))]
        RequiresMark = 9,

        [Name("User disabled", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_USER_DISABLED_NAME))]
        [ExtendedDescription("The user account is disabled", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_USER_DISABLED_DESCRIPTION))]
        UserDisabled = 10,

        [Name("Mark already used", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_MARK_ALREADY_USED_NAME))]
        [ExtendedDescription("The mark is already assigned to another product", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_MARK_ALREADY_USED_DESCRIPTION))]
        MarkAlreadyUsed = 11,

        [Name("Sale restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_SALE_RESTRICTED_NAME))]
        [ExtendedDescription("The product sale is restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_SALE_RESTRICTED_DESCRIPTION))]
        SaleRestricted = 12,

        [Name("Client order restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_CLIENT_ORDER_RESTRICTED_NAME))]
        [ExtendedDescription("The product cannot be ordered from the client", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_CLIENT_ORDER_RESTRICTED_DESCRIPTION))]
        ClientOrderRestricted = 13,

        [Name("Fiscal payment method required", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_FISCAL_PAYMENT_METHOD_REQUIRED_NAME))]
        [ExtendedDescription("The sale of a marked product requires a fiscal payment method", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_FISCAL_PAYMENT_METHOD_REQUIRED_DESCRIPTION))]
        FiscalPaymentMethodRequired = 14,
    }
}
