using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    public enum CartErrorCode
    {
        /// <summary>
        /// Specified cart id is invalid.
        /// </summary>
        [Name("Invalid cart", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ID_NAME))]
        [ExtendedDescription("The cart is invalid or expired", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_DESCRIPTION))]
        InvalidCartId = 0,

        [Name("Invalid cart entry id", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ENTRY_ID_NAME))]
        [ExtendedDescription("The cart entry id specified is invalid", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_INVALID_CART_ENTRY_ID_DESCRIPTION))]
        InvalidCartEntryId = 1,

        /// <summary>
        /// Action is not supported.
        /// </summary>
        [Name("Not supported", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_NAME))]
        [ExtendedDescription("Cart action is not supported", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_NOT_SUPPORTED_DESCRIPTION))]
        NotSupported = 2,

        [Name("Time restricted", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_TIME_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by time or date", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_TIME_RESTRICTED_DESCRIPTION))]
        TimeRestricted = 3,

        [Name("User group restricted", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_USER_GROUP_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by user group", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_USER_GROUP_RESTRICTED_DESCRIPTION))]
        UserGroupRestricted = 4,

        [Name("Branch restricted", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_BRANCH_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by branch", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_BRANCH_RESTRICTED_DESCRIPTION))]
        BranchRestricted = 5,

        [Name("Age restricted", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_CART_AGE_RESTRICTED_NAME))]
        [ExtendedDescription("The purchase is restricted by age", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_WAITING_LINE_AGE_RESTRICTED_DESCRIPTION))]
        AgeRestricted = 6,
    }
}
