using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Companion error codes.
    /// </summary>
    public enum CompanionExceptionErrorCode
    {
        /// <summary>
        /// Fiscal printer is not connected.
        /// </summary>
        [Name("Companion not connected", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_NOT_CONNECTED_NAME))]
        [ExtendedDescription("Cannot perform the action because the companion is not connected", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_NOT_CONNECTED_DESCRIPTION))]
        NotConnected = 0,

        /// <summary>
        /// Shift is expired.
        /// </summary>
        [Name("Fiscal printer shift expired", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_DEVICE_SHIFT_EXPIRED_NAME))]
        [ExtendedDescription("Cannot perform the action because the fiscal printer shift is expired", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_DEVICE_SHIFT_EXPIRED_DESCRIPTION))]
        ShiftExpired = 1,

        /// <summary>
        /// Shift is closed.
        /// </summary>
        [Name("Device shift closed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_DEVICE_SHIFT_CLOSED_NAME))]
        [ExtendedDescription("Cannot perform the action because the fiscal device shift is closed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_DEVICE_SHIFT_CLOSED_DESCRIPTION))]
        ShiftClosed = 2,  

        /// <summary>
        /// Fiscal printer error.
        /// </summary>
        [Name("Fiscal printer error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_FISCAL_PRINTER_ERROR_NAME))]
        [ExtendedDescription("Cannot perform the action due to fiscal printer error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_FISCAL_PRINTER_ERROR_DESCRIPTION))]
        FiscalPrinterError = 3,

        /// <summary>
        /// Payment terminal error.
        /// </summary>
        [Name("Payment terminal error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_PAYMENT_TERMINAL_ERROR_NAME))]
        [ExtendedDescription("Cannot perform the action due to payment terminal error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_PAYMENT_TERMINAL_ERROR_DESCRIPTION))]
        PaymentTerminalError = 4,

        /// <summary>
        /// Qr display error.
        /// </summary>
        [Name("QR display error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_QR_DISPLAY_ERROR_NAME))]
        [ExtendedDescription("Cannot perform the action due to qr display error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_QR_DISPLAY_ERROR_DESCRIPTION))]
        QrDisplayError = 5,

        /// <summary>
        /// Companion is not configured.
        /// </summary>
        /// <remarks>
        /// This error code is used when no companion device has been specified for an operation that requires one.
        /// </remarks>
        [Name("Companion required", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_REQUIRED_ERROR_NAME))]
        [ExtendedDescription("Cannot perform the action due to missing companion configuration", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_REQUIRED_ERROR_DESCRIPTION))]
        CompanionRequired = 6,

        /// <summary>
        /// Shift is already open.
        /// </summary>
        /// <remarks>
        /// This error code is used when attempting to open a shift that is already open.
        /// </remarks>
        [Name("Device shift open", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_DEVICE_SHIFT_OPEN_NAME))]
        [ExtendedDescription("Cannot open the shift because the device shift is already open", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_DEVICE_SHIFT_OPEN_DESCRIPTION))]
        ShiftOpen = 7,

        /// <summary>
        /// No cashier can be attributed to the fiscal receipt.
        /// </summary>
        /// <remarks>
        /// This error code is used when a fiscal receipt will be owed for a transaction that has no operator of its own
        /// (self service) and the register that would print it has no default operator to sign the receipt with.
        /// </remarks>
        [Name("No cashier", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_NO_CASHIER_NAME))]
        [ExtendedDescription("Cannot perform the action because no cashier can be attributed to the fiscal receipt", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_NO_CASHIER_DESCRIPTION))]
        NoCashier = 8,

        /// <summary>
        /// Tax configuration required for the fiscal receipt is incomplete.
        /// </summary>
        /// <remarks>
        /// This error code is used when a fiscal receipt will be owed for a transaction but the tax system or VAT rate
        /// it must be generated with is not configured for the branch.
        /// </remarks>
        [Name("Tax configuration incomplete", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_TAX_CONFIGURATION_INCOMPLETE_NAME))]
        [ExtendedDescription("Cannot perform the action because the tax configuration required for the fiscal receipt is incomplete", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_COMPANION_TAX_CONFIGURATION_INCOMPLETE_DESCRIPTION))]
        TaxConfigurationIncomplete = 9
    }
}
