using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Inventory exception error codes.
    /// </summary>
    public enum InventoryExceptionErrorCode
    {
        /// <summary>
        /// Transfer already completed.
        /// </summary>
        [Name("Transfer already completed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVENTORY_TRANSFER_ALREADY_COMPLETED_NAME))]
        [ExtendedDescription("Cannot process already completed transfer", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVENTORY_TRANSFER_ALREADY_COMPLETED_DESCRIPTION))]
        TransferAlreadyCompleted = 0,

        /// <summary>
        /// Same stock transfer.
        /// </summary>
        [Name("Same stock transfer not allowed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVENTORY_SAME_STOCK_TRANSFER_NAME))]
        [ExtendedDescription("Cannot make transfer to same stock", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVENTORY_SAME_STOCK_TRANSFER_DESCRIPTION))]
        SameStockTransfer = 1,
    }
}
