using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Inventory exception error codes.
    /// </summary>
    public enum InventoryExceptionErrorCode
    {
        /// <summary>
        /// Transfer already completed.
        /// </summary>
        [Name("Transfer already completed", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVENTORY_TRANSFER_ALREADY_COMPLETED_NAME))]
        [ExtendedDescription("Cannot process already completed transfer", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVENTORY_TRANSFER_ALREADY_COMPLETED_DESCRIPTION))]
        TransferAlreadyCompleted = 0,
    }
}
