using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Invoice error codes.
    /// </summary>
    public enum InvoiceExceptionErrorCode
    {
        /// <summary>
        /// Set when invoice status is already set to paid and we try to execute a payment on it.
        /// </summary>
        [Name("Invoice already paid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_ALREADY_PAID_NAME))]
        [ExtendedDescription("Cannot execute payment on invoice that is already paid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_ALREADY_PAID_DESCRIPTION))]
        AlreadyPaid = 0,

        /// <summary>
        /// Set when we try to fully repay an invoice with amount less than outstanding amount.
        /// </summary>
        [Name("Amount is less than outstanding", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_AMOUNT_LESS_THAN_OUTSTANDING_NAME))]
        [ExtendedDescription("Cannot repay an invoice with amount less than outstanding amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_AMOUNT_LESS_THAN_OUTSTANDING_DESCRIPTION))]
        AmountLessThanOutstanding = 1,

        /// <summary>
        /// Set when we try to perform an action on a void invoice.
        /// </summary>
        [Name("Void invoice", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_VOID_NAME))]
        [ExtendedDescription("Cannot perform the action on a void invoice", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_VOID_DESCRIPTION))]
        Void = 2,

        /// <summary>
        /// Set when we try to create an invoice for a user with disabled credit.
        /// </summary>
        [Name("User with no credit", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_NO_CREDIT_NAME))]
        [ExtendedDescription("Cannot create an invoice for a user with disabled credit", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_NO_CREDIT_DESCRIPTION))]
        NoCredit = 3,

        /// <summary>
        /// Set when invoice would cause user to exceed credit limit.
        /// </summary>
        [Name("User credit limit reached", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_CREDIT_LIMIT_REACHED_NAME))]
        [ExtendedDescription("The invoice would cause user to exceed credit limit", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_CREDIT_LIMIT_REACHED_DESCRIPTION))]
        CreditLimitReached = 4,
    }
}
