using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Invoice payment error code.
    /// </summary>
    public enum InvoicePaymentExceptionErrorCode
    {
        /// <summary>
        /// Set on unspecified error.
        /// </summary>
        [Localized("UNSPECIFIED")]
        [Name("Invoice payment unspecified error", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_UNSPECIFIED_NAME))]
        [ExtendedDescription("Unspecified error while executing invoice payment", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_UNSPECIFIED_DESCRIPTION))]
        Unspecified = 0,

        /// <summary>
        /// Set when invoice payment amount equals zero.
        /// </summary>
        [Name("Invoice payment amount zero or less", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_AMOUNT_ZERO_OR_LESS_NAME))]
        [ExtendedDescription("Cannot execute invoice payment with amount zero or less", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_AMOUNT_ZERO_OR_LESS_DESCRIPTION))]
        AmountZeroOrLess,

        /// <summary>
        /// Set when outstanding amount is zero.
        /// </summary>
        [Name("Invoice payment outstanding amount zero", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_OUTSTANDING_AMOUNT_ZERO_NAME))]
        [ExtendedDescription("Cannot execute invoice payment when outstanding amount is zero", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_OUTSTANDING_AMOUNT_ZERO_DESCRIPTION))]
        OutstandingAmountZero,

        /// <summary>
        /// Set when outstanding amount is less than the payment amount.
        /// </summary>
        [Name("Invoice payment outstanding amount less", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_OUTSTANDING_AMOUNT_LESS_NAME))]
        [ExtendedDescription("Cannot execute invoice payment when outstanding amount is less than payment amount", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_PAYMENT_OUTSTANDING_AMOUNT_LESS_DESCRIPTION))]
        OutstandingAmountLess,
    }
}
