using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Invoice error codes.
    /// </summary>
    public enum InvoiceExceptionErrorCode
    {
        /// <summary>
        /// Set when invoice status is already set to paid and we try to execute a payment on it.
        /// </summary>
        [Name("Invoice already paid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_ALREADY_PAID_NAME))]
        [ExtendedDescription("Cannot execute payment on invoice that is already paid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_ALREADY_PAID_DESCRIPTION))]
        AlreadyPaid = 0,

        /// <summary>
        /// Set when we try to fully repay an invoice with amount less than outstanding amount.
        /// </summary>
        [Name("Amount is less than outstanding", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_AMOUNT_LESS_THAN_OUTSTANDING_NAME))]
        [ExtendedDescription("Cannot repay an invoice with amount less than outstanding amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_AMOUNT_LESS_THAN_OUTSTANDING_DESCRIPTION))]
        AmountLessThanOutstanding = 1,

        /// <summary>
        /// Set when we try to perform an action on a voided transaction (invoice or deposit payment) — e.g.
        /// re-voiding it, or paying a voided invoice. Shared across the invoice and deposit-payment paths.
        /// </summary>
        [Name("Voided transaction", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_VOID_NAME))]
        [ExtendedDescription("Cannot perform the action because the transaction is already voided", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_VOID_DESCRIPTION))]
        Void = 2,

        /// <summary>
        /// Set when we try to create an invoice for a user with disabled credit.
        /// </summary>
        [Name("User with no credit", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_NO_CREDIT_NAME))]
        [ExtendedDescription("Cannot create an invoice for a user with disabled credit", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_NO_CREDIT_DESCRIPTION))]
        NoCredit = 3,

        /// <summary>
        /// Set when invoice would cause user to exceed credit limit.
        /// </summary>
        [Name("User credit limit reached", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_CREDIT_LIMIT_REACHED_NAME))]
        [ExtendedDescription("The invoice would cause user to exceed credit limit", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_CREDIT_LIMIT_REACHED_DESCRIPTION))]
        CreditLimitReached = 4,

        /// <summary>
        /// Set when fiscalization is enabled and the sale fiscal receipt is still printing
        /// (Pending/EReceiptPending), so a refund cannot be performed yet — the sale must finish printing
        /// (or fail) first, otherwise refunding now would race the fiscal generator and leave a printed sale
        /// with no matching return receipt. Transient: retry once printing completes.
        /// Shared by the invoice and deposit-payment refund paths (a deposit payment carries a sale receipt too).
        /// </summary>
        [Name("Sale receipt still printing", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_RECEIPT_PENDING_NAME))]
        [ExtendedDescription("Cannot refund while the sale fiscal receipt is still printing; retry once printing completes", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_RECEIPT_PENDING_DESCRIPTION))]
        ReceiptPending = 5,

        /// <summary>
        /// Set when fiscalization is enabled and the sale fiscal receipt is in an inconsistent state that can
        /// neither be reversed (it lacks a usable signature) nor safely treated as never-fiscalized — for
        /// example a receipt marked Printed but carrying no signature, or of the wrong type. Not transient:
        /// requires manual/support resolution rather than a retry.
        /// Shared by the invoice and deposit-payment refund paths (a deposit payment carries a sale receipt too).
        /// </summary>
        [Name("Sale receipt invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_RECEIPT_INVALID_NAME))]
        [ExtendedDescription("Cannot refund because the sale fiscal receipt is in an inconsistent state and cannot be reversed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_INVOICE_RECEIPT_INVALID_DESCRIPTION))]
        ReceiptInvalid = 6,
    }
}
