using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Payment error codes.
    /// </summary>
    public enum PaymentExceptionErrorCode
    {
        /// <summary>
        /// Set on unspecified error.
        /// </summary>
        [Name("Payment unspecified error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_UNSPECIFIED_NAME))]
        [ExtendedDescription("Unspecified error while executing payment", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_UNSPECIFIED_DESCRIPTION))]
        Unspecified = 0,

        /// <summary>
        /// Set when there are no funds available to execute this payment.
        /// </summary>
        [Name("Payment insufficient funds", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_INSUFFICIENT_FUNDS_NAME))]
        [ExtendedDescription("The user has no funds to execute the payment", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_INSUFFICIENT_FUNDS_DESCRIPTION))]
        InsufficientFunds = 1,

        /// <summary>
        /// Set when payment amount equals zero or less. Zero payments not allowed.
        /// </summary>
        [Name("Payment amount zero or less", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_ZERO_OR_LESS_NAME))]
        [ExtendedDescription("Cannot execute payment with amount zero or less", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_ZERO_OR_LESS_DESCRIPTION))]
        AmountZeroOrLess = 2,

        /// <summary>
        /// Set when amount received is less than actual payment amount.
        /// </summary>
        [Name("Payment received amount is less than payment amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_RECEIVED_LESS_NAME))]
        [ExtendedDescription("The amount received is less than actual payment amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_RECEIVED_LESS_DESCRIPTION))]
        AmountReceivedLess = 3,

        /// <summary>
        /// Set when we try to execute a payment with an method that is invalid for payment transaction.
        /// </summary>
        [Localized("PAYMENTERRORCODE_INALID_PAYMENT_METHOD")]
        [Name("Invalid payment method", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_INVALID_PAYMENT_METHOD_NAME))]
        [ExtendedDescription("Cannot execute payment because the payment method is invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_INVALID_PAYMENT_METHOD_DESCRIPTION))]
        InvalidPaymentMethod = 4,

        [Name("Payments exceeds outstanding amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_PAYMENTS_EXCEED_OUTSTANDING_NAME))]
        [ExtendedDescription("Cannot execute payment because the payment exceeds outstanding", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_INVALID_PAYMENT_METHOD_DESCRIPTION))]
        ExceedOutstanding = 5,

        /// <summary>
        /// Set when the amount is lower than the configured minimum top up value.
        /// </summary>
        [Name("Payment amount below minimum", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_BELOW_MINIMUM_NAME))]
        [ExtendedDescription("Cannot execute payment because the amount is below the configured minimum", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_BELOW_MINIMUM_DESCRIPTION))]
        AmountBelowMinimum = 6,

        /// <summary>
        /// Set when the amount is higher than the configured maximum top up value.
        /// </summary>
        [Name("Payment amount above maximum", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_ABOVE_MAXIMUM_NAME))]
        [ExtendedDescription("Cannot execute payment because the amount is above the configured maximum", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_AMOUNT_ABOVE_MAXIMUM_DESCRIPTION))]
        AmountAboveMaximum = 7,

        /// <summary>
        /// Set when a custom amount is used while only the preset amounts are allowed.
        /// </summary>
        [Name("Custom payment amount not allowed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_CUSTOM_AMOUNT_NOT_ALLOWED_NAME))]
        [ExtendedDescription("Cannot execute payment because only the preset amounts are allowed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PAYMENT_CUSTOM_AMOUNT_NOT_ALLOWED_DESCRIPTION))]
        CustomAmountNotAllowed = 8,
    }
}
