using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Points transaction error codes.
    /// </summary>
    public enum PointTransactionExceptionErrorCode
    {
        /// <summary>
        /// Unspecified.
        /// </summary>
        [Localized("UNSPECIFIED")]
        [Name("Point transaction unspecified error", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_UNSPECIFIED_NAME))]
        [ExtendedDescription("Unspecified error while executing point transaction", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_UNSPECIFIED_DESCRIPTION))]
        Unspecified = 0,

        /// <summary>
        /// Set when we try to execute transaction with zero amount.
        /// </summary>
        [Name("Point transaction amount zero or less", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_AMOUNT_ZERO_OR_LESS_NAME))]
        [ExtendedDescription("Cannot execute point transaction with amount zero or less", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_AMOUNT_ZERO_OR_LESS_DESCRIPTION))]
        AmountZeroOrLess = 1,

        /// <summary>
        /// Set when user has no funds to execute the transaction.
        /// </summary>
        [Name("Point transaction insufficient funds", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_INSUFFICIENT_FUNDS_NAME))]
        [ExtendedDescription("The user has no funds to execute the point transaction", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_INSUFFICIENT_FUNDS_DESCRIPTION))]
        InsufficientFunds = 2,

        /// <summary>
        /// Transaction type not supported.
        /// </summary>
        [Name("Point transaction type not supported", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_TRANSACTION_TYPE_NOT_SUPPORTED_NAME))]
        [ExtendedDescription("The specified point transaction type is not supported for the specified user", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_POINT_TRANSACTION_TRANSACTION_TYPE_NOT_SUPPORTED_DESCRIPTION))]
        TransactionTypeNotSupported = 3,
    }
}
