using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Promotion related error codes.
    /// </summary>
    public enum PromotionErrorCode
    {
        [Name("Promotion code is invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_CODE_INVALID_NAME))]
        [ExtendedDescription("The promotion code specified is invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_CODE_INVALID_DESCRIPTION))]
        InvalidCode = 0,

        [Name("Promotion inactive", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_INACITVE_NAME))]
        [ExtendedDescription("The promotion is inactive", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_INACITVE_DESCRIPTION))]
        Inactive = 1,
    }
}
