using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Promotion related error codes.
    /// </summary>
    public enum PromotionErrorCode
    {
        [Name("Promotion code is invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_CODE_INVALID_NAME))]
        [ExtendedDescription("The promotion code specified is invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_CODE_INVALID_DESCRIPTION))]
        InvalidCode = 0,

        [Name("Promotion inactive", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_INACTIVE_NAME))]
        [ExtendedDescription("The promotion is inactive", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_INACTIVE_DESCRIPTION))]
        Inactive = 1,

        [Name("Promotion branch restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_BRANCH_RESTRICTED_NAME))]
        [ExtendedDescription("The promotion is not available for this branch", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_BRANCH_RESTRICTED_DESCRIPTION))]
        BranchRestricted = 2,

        [Name("Promotion period restricted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_PERIOD_RESTRICTED_NAME))]
        [ExtendedDescription("The promotion is not available at this time", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_PERIOD_RESTRICTED_DESCRIPTION))]
        PeriodRestricted = 3,

        [Name("Promotion total limit exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_TOTAL_LIMIT_EXCEEDED_NAME))]
        [ExtendedDescription("The promotion total usage limit has been exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_TOTAL_LIMIT_EXCEEDED_DESCRIPTION))]
        TotalLimitExceeded = 4,

        [Name("Promotion per-user limit exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_PER_USER_LIMIT_EXCEEDED_NAME))]
        [ExtendedDescription("The promotion per-user usage limit has been exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_PER_USER_LIMIT_EXCEEDED_DESCRIPTION))]
        PerUserLimitExceeded = 5,

        [Name("Promotion daily limit exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_DAILY_LIMIT_EXCEEDED_NAME))]
        [ExtendedDescription("The promotion daily usage limit has been exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_DAILY_LIMIT_EXCEEDED_DESCRIPTION))]
        DailyLimitExceeded = 6,

        [Name("Promotion weekly limit exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_WEEKLY_LIMIT_EXCEEDED_NAME))]
        [ExtendedDescription("The promotion weekly usage limit has been exceeded", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_PROMOTION_WEEKLY_LIMIT_EXCEEDED_DESCRIPTION))]
        WeeklyLimitExceeded = 7,
    }
}
