using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Refund related error codes.
    /// </summary>
    public enum RefundExceptionErrorCode
    {
        [Name("Refund amount exceeds max", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_AMOUNT_EXCEEDS_MAX_NAME))]
        [ExtendedDescription("The refund amount exceeds the maximum allowed for this invoice", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_AMOUNT_EXCEEDS_MAX_DESCRIPTION))]
        AmountExceedsMax = 0,

        [Name("Refund method not allowed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_METHOD_NOT_ALLOWED_NAME))]
        [ExtendedDescription("The specified refund method is not allowed for this invoice", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_METHOD_NOT_ALLOWED_DESCRIPTION))]
        MethodNotAllowed = 1,

        [Name("Refund exceeds payment remaining", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_EXCEEDS_PAYMENT_REMAINING_NAME))]
        [ExtendedDescription("The refund amount exceeds the original payment remaining refundable amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_EXCEEDS_PAYMENT_REMAINING_DESCRIPTION))]
        ExceedsPaymentRemaining = 2,

        [Name("Refund exceeds invoice payment remaining", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_EXCEEDS_INVOICE_PAYMENT_REMAINING_NAME))]
        [ExtendedDescription("The refund amount exceeds the invoice payment remaining refundable amount", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_REFUND_EXCEEDS_INVOICE_PAYMENT_REMAINING_DESCRIPTION))]
        ExceedsInvoicePaymentRemaining = 3,
    }
}
