using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions.Errors
{
    /// <summary>
    /// Remote control exception codes.
    /// </summary>
    public enum RemoteControlExceptionErrorCode
    {
        /// <summary>
        /// Generic error.
        /// </summary>
        [Name("Remote control unspecified error", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_ERROR_NAME))]
        [ExtendedDescription("Unspecified error while executing remote control", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_ERROR_DESCRIPTION))]
        Error = 0,

        /// <summary>
        /// Invalid host id was provided.
        /// </summary>
        [Name("Remote control invalid host id", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_INVALID_HOST_ID_NAME))]
        [ExtendedDescription("The specified host id is invalid", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_INVALID_HOST_ID_DESCRIPTION))]
        InvalidHostId = 1,

        /// <summary>
        /// Host is not connected.
        /// </summary>
        [Name("Remote control host is not connected", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_HOST_NOT_CONNECTED_NAME))]
        [ExtendedDescription("The specified host is not connected", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_HOST_NOT_CONNECTED_DESCRIPTION))]
        HostNotConnected = 2,

        /// <summary>
        /// Session initiation error.
        /// </summary>
        [Name("Remote control session initiation error", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_SESSION_INITIATION_ERROR_NAME))]
        [ExtendedDescription("Cannot initiate remote control session", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_SESSION_INITIATION_ERROR_DESCRIPTION))]
        SessionInitiationError = 3,

        /// <summary>
        /// Not supported by client host.
        /// </summary>
        [Name("Remote control not supported", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_NOT_SUPPORTED_NAME))]
        [ExtendedDescription("The specified host does not support remote control", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_REMOTE_CONTROL_NOT_SUPPORTED_DESCRIPTION))]
        NotSupported = 4,
    }
}
