using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Reservation error codes.
    /// </summary>
    public enum ReservationExceptionErrorCode
    {
        /// <summary>
        /// Entry already added to reservation.
        /// </summary>
        [Name("Reservation entry already added", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_ALREADY_ADDED_NAME))]
        [ExtendedDescription("Cannot perform the action because the host or the user is already added", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_ALREADY_ADDED_DESCRIPTION))]
        AlreadyAdded = 0,

        /// <summary>
        /// Entry not present.
        /// </summary>
        [Name("Reservation entry not present", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_NOT_PRESENT_NAME))]
        [ExtendedDescription("Cannot perform the action because the host or the user is not present", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_NOT_PRESENT_DESCRIPTION))]
        NotPresent = 1,

        /// <summary>
        /// Reservation is inactive.
        /// </summary>
        [Name("Reservation is inactive", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_RESERVATION_INACTIVE_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation is inactive", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_RESERVATION_INACTIVE_DESCRIPTION))]
        ReservationInactive = 2,

        /// <summary>
        /// Invalid reservation date.
        /// </summary>
        [Name("Invalid reservation date", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DATE_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation has invalid date", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DATE_DESCRIPTION))]
        InvalidDate = 3,

        /// <summary>
        /// Invalid reservation duration.
        /// </summary>
        [Name("Invalid reservation duration", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DURATION_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation has invalid duration", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DURATION_DESCRIPTION))]
        InvalidDuration = 4,

        /// <summary>
        /// Reservation overlaps.
        /// </summary>
        [Name("Reservation overlaps", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_OVERLAP_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation overlaps another reservation", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_OVERLAP_DESCRIPTION))]
        Overlap = 5,

        /// <summary>
        /// Reservation finalized.
        /// </summary>
        [Name("Reservation finalized", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_FINALIZED_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation is already finalized", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_FINALIZED_DESCRIPTION))]
        Finalized = 6,

        /// <summary>
        /// Invalid parameters.
        /// </summary>
        [Name("Invalid parameters", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_PARAMETERS_NAME))]
        [ExtendedDescription("Parameters are invalid", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_PARAMETERS_DESCRIPTION))]
        InvalidParameters = 7,

        /// <summary>
        /// Multi host not allowed.
        /// </summary>
        [Name("Multi host not allowed", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_MULTI_HOST_NOT_ALLOWED_NAME))]
        [ExtendedDescription("Reservation is only allowed for single host", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_MULTI_HOST_NOT_ALLOWED_DESCRIPTION))]
        MultiHostNotAllowed = 8,
    }
}
