using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Reservation error codes.
    /// </summary>
    public enum ReservationExceptionErrorCode
    {
        /// <summary>
        /// Entry already added to reservation.
        /// </summary>
        [Name("Reservation entry already added", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_ALREADY_ADDED_NAME))]
        [ExtendedDescription("Cannot perform the action because the host or the user is already added", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_ALREADY_ADDED_DESCRIPTION))]
        AlreadyAdded = 0,

        /// <summary>
        /// Entry not present.
        /// </summary>
        [Name("Reservation entry not present", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_NOT_PRESENT_NAME))]
        [ExtendedDescription("Cannot perform the action because the host or the user is not present", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_NOT_PRESENT_DESCRIPTION))]
        NotPresent = 1,

        /// <summary>
        /// Reservation is inactive.
        /// </summary>
        [Name("Reservation is inactive", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_RESERVATION_INACTIVE_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation is inactive", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_RESERVATION_INACTIVE_DESCRIPTION))]
        ReservationInactive = 2,

        /// <summary>
        /// Invalid reservation date.
        /// </summary>
        [Name("Invalid reservation date", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DATE_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation has invalid date", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DATE_DESCRIPTION))]
        InvalidDate = 3,

        /// <summary>
        /// Invalid reservation duration.
        /// </summary>
        [Name("Invalid reservation duration", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DURATION_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation has invalid duration", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_DURATION_DESCRIPTION))]
        InvalidDuration = 4,

        /// <summary>
        /// Reservation overlaps.
        /// </summary>
        [Name("Reservation overlaps", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_OVERLAP_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation overlaps another reservation", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_OVERLAP_DESCRIPTION))]
        Overlap = 5,

        [Name("Reservation finalized", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_FINALIZED_NAME))]
        [ExtendedDescription("Cannot perform the action because the reservation is already finalized", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_FINALIZED_DESCRIPTION))]
        Finalized = 6,

        [Name("Invalid parameters", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_PARAMETERS_NAME))]
        [ExtendedDescription("Parameters are invalid", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_RESERVATION_INVALID_PARAMETERS_DESCRIPTION))]
        InvalidParameters = 7,

        MultiHostDisabled = 8,
    }
}
