using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Shift error codes.
    /// </summary>
    public enum ShiftExceptionErrorCode
    {
        /// <summary>
        /// No active shift.
        /// </summary>
        [Localized("SHIFT_ERROR_NO_ACTIVE_SHIFT")]
        [Name("No active shift", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_NO_ACTIVE_SHIFT_NAME))]
        [ExtendedDescription("Cannot perform the action because there is no active shift", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_NO_ACTIVE_SHIFT_DESCRIPTION))]
        NoActiveShift = 0,

        /// <summary>
        /// Another shift.
        /// </summary>
        [Localized("SHIFT_ERROR_ANOTHER_ACTIVE")]
        [Name("Another shift", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_ANOTHER_SHIFT_NAME))]
        [ExtendedDescription("Cannot perform the action because there is another shift", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_ANOTHER_SHIFT_DESCRIPTION))]
        AnotherShift = 1,

        /// <summary>
        /// Already active.
        /// </summary>
        [Localized("SHIFT_ERROR_ALREADY_ACTIVE")]
        [Name("Shift already active", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_ALREADY_ACTIVE_NAME))]
        [ExtendedDescription("Cannot perform the action because the shift is already active", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_ALREADY_ACTIVE_DESCRIPTION))]
        AlreadyActive = 2,

        /// <summary>
        /// No register.
        /// </summary>
        [Localized("SHIFT_ERROR_NO_REGISTER")]
        [Name("No register", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_NO_REGISTER_NAME))]
        [ExtendedDescription("Cannot perform the action because there is no register", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_NO_REGISTER_DESCRIPTION))]
        NoRegister = 3,

        /// <summary>
        /// Invalid shift id.
        /// </summary>
        [Localized("SHIFT_ERROR_INVALID_ID")]
        [Name("Invalid shift id", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_INVALID_SHIFT_ID_NAME))]
        [ExtendedDescription("Cannot perform the action because the shift id is invalid", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_INVALID_SHIFT_ID_DESCRIPTION))]
        InvalidShiftId = 4,

        /// <summary>
        /// Already ended.
        /// </summary>
        [Localized("SHIFT_ERROR_ALREADY_ENDED")]
        [Name("Shift already ended", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_ALREADY_ENDED_NAME))]
        [ExtendedDescription("Cannot perform the action because the shift is already ended", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_ALREADY_ENDED_DESCRIPTION))]
        AlreadyEnded = 5,

        /// <summary>
        /// Shift disabled.
        /// </summary>
        [Localized("SHIFT_ERROR_DISABLED")]
        [Name("Shift is disabled", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_SHIFT_DISABLED_NAME))]
        [ExtendedDescription("Cannot perform the action because the shift is disabled", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_SHIFT_DISABLED_DESCRIPTION))]
        ShiftDisabled = 6,

        /// <summary>
        /// No operator.
        /// </summary>
        [Localized("SHIFT_ERROR_NO_OPERATOR")]
        [Name("No operator", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_NO_OPERATOR_NAME))]
        [ExtendedDescription("Cannot perform the action because there is no operator", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_NO_OPERATOR_DESCRIPTION))]
        NoOperator = 7,

        /// <summary>
        /// Shift ending.
        /// </summary>
        [Localized("SHIFT_ERROR_ENDING")]
        [Name("Shift ending", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_SHIFT_ENDING_NAME))]
        [ExtendedDescription("Cannot perform the action because the shift is ending", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_SHIFT_ENDING_DESCRIPTION))]
        ShiftEnding = 8,

        /// <summary>
        /// Shift not ending.
        /// </summary>
        [Localized("SHIFT_ERROR_NOT_ENDING")]
        [Name("Shift not ending", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_SHIFT_NOT_ENDING_NAME))]
        [ExtendedDescription("Cannot perform the action because the shift is not ending", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_SHIFT_NOT_ENDING_DESCRIPTION))]
        ShiftNotEnding = 9,

        /// <summary>
        /// Deleted register.
        /// </summary>
        [Localized("SHIFT_ERROR_DELETED_REGISTER")]
        [Name("Deleted register", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_DELETED_REGISTER_NAME))]
        [ExtendedDescription("Cannot perform the action because the register is deleted", nameof(Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_DELETED_REGISTER_DESCRIPTION))]
        DeletedRegister = 10,
    }
}
