using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{    
    public enum StockCountErrorCodes
    {
        [Name("Already counted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_DELETED_REGISTER_NAME))]
        [ExtendedDescription("Cannot perform the action because stock is already counted", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_SHIFT_DELETED_REGISTER_DESCRIPTION))]
        AlreadyCounted = 0,
    }
}
