using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// User group error codes.
    /// </summary>
    public enum UserGroupExceptionErrorCode
    {
        /// <summary>
        /// Set when we try to perform an action on the wrong type of user group.
        /// </summary>
        [Name("User group invalid type", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_USER_GROUP_INVALID_TYPE_NAME))]
        [ExtendedDescription("Cannot perform the action on the specified user group type", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_ERROR_USER_GROUP_INVALID_TYPE_DESCRIPTION))]
        InvalidType = 0,

        /// <summary>
        /// Set when there is no useable guest group for an operation.
        /// </summary>
        NoGuestGroup = 1,
    }
}
