//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Server.Resources.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Server.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset is already checked in.
        /// </summary>
        public static string EXCEPTION_ERROR_ASSET_ALREADY_CHECKED_IN_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ASSET_ALREADY_CHECKED_IN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets already checked in.
        /// </summary>
        public static string EXCEPTION_ERROR_ASSET_ALREADY_CHECKED_IN_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ASSET_ALREADY_CHECKED_IN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset is disabled.
        /// </summary>
        public static string EXCEPTION_ERROR_ASSET_DISABLED_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ASSET_DISABLED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets is disabled.
        /// </summary>
        public static string EXCEPTION_ERROR_ASSET_DISABLED_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ASSET_DISABLED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset is not checked in.
        /// </summary>
        public static string EXCEPTION_ERROR_ASSET_NOT_CHECKED_IN_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ASSET_NOT_CHECKED_IN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets not checked in.
        /// </summary>
        public static string EXCEPTION_ERROR_ASSET_NOT_CHECKED_IN_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR_ASSET_NOT_CHECKED_IN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets related error.
        /// </summary>
        public static string EXCEPTION_TYPE_ASSET_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ASSET_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets error.
        /// </summary>
        public static string EXCEPTION_TYPE_ASSET_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ASSET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request related error.
        /// </summary>
        public static string EXCEPTION_TYPE_ASSISTANCE_REQUEST_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ASSISTANCE_REQUEST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request error.
        /// </summary>
        public static string EXCEPTION_TYPE_ASSISTANCE_REQUEST_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ASSISTANCE_REQUEST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing profile related error.
        /// </summary>
        public static string EXCEPTION_TYPE_BILLING_PROFILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_BILLING_PROFILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing profile error.
        /// </summary>
        public static string EXCEPTION_TYPE_BILLING_PROFILE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_BILLING_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit related error.
        /// </summary>
        public static string EXCEPTION_TYPE_DEPOSIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_DEPOSIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit error.
        /// </summary>
        public static string EXCEPTION_TYPE_DEPOSIT_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_DEPOSIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity in use related error.
        /// </summary>
        public static string EXCEPTION_TYPE_ENTITY_IN_USE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ENTITY_IN_USE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity in use error.
        /// </summary>
        public static string EXCEPTION_TYPE_ENTITY_IN_USE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ENTITY_IN_USE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not referenced related error.
        /// </summary>
        public static string EXCEPTION_TYPE_ENTITY_NOT_REFERENCED_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ENTITY_NOT_REFERENCED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not referenced error.
        /// </summary>
        public static string EXCEPTION_TYPE_ENTITY_NOT_REFERENCED_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ENTITY_NOT_REFERENCED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity reference related error.
        /// </summary>
        public static string EXCEPTION_TYPE_ENTITY_REFERENCE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ENTITY_REFERENCE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity reference error.
        /// </summary>
        public static string EXCEPTION_TYPE_ENTITY_REFERENCE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ENTITY_REFERENCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal printer related error.
        /// </summary>
        public static string EXCEPTION_TYPE_FISCAL_PRINTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_FISCAL_PRINTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal printer error.
        /// </summary>
        public static string EXCEPTION_TYPE_FISCAL_PRINTER_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_FISCAL_PRINTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host reservation related error.
        /// </summary>
        public static string EXCEPTION_TYPE_HOST_RESERVATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_HOST_RESERVATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host reservation error.
        /// </summary>
        public static string EXCEPTION_TYPE_HOST_RESERVATION_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_HOST_RESERVATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http response related error.
        /// </summary>
        public static string EXCEPTION_TYPE_HTTP_RESPONSE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_HTTP_RESPONSE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http response error.
        /// </summary>
        public static string EXCEPTION_TYPE_HTTP_RESPONSE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_HTTP_RESPONSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property related error.
        /// </summary>
        public static string EXCEPTION_TYPE_INVALID_PROPERTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_INVALID_PROPERTY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property error.
        /// </summary>
        public static string EXCEPTION_TYPE_INVALID_PROPERTY_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_INVALID_PROPERTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice related error.
        /// </summary>
        public static string EXCEPTION_TYPE_INVOICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_INVOICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice error.
        /// </summary>
        public static string EXCEPTION_TYPE_INVOICE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_INVOICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice payment related error.
        /// </summary>
        public static string EXCEPTION_TYPE_INVOICE_PAYMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_INVOICE_PAYMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice payment error.
        /// </summary>
        public static string EXCEPTION_TYPE_INVOICE_PAYMENT_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_INVOICE_PAYMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License reservation related error.
        /// </summary>
        public static string EXCEPTION_TYPE_LICENSE_RESERVATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_LICENSE_RESERVATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License reservation error.
        /// </summary>
        public static string EXCEPTION_TYPE_LICENSE_RESERVATION_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_LICENSE_RESERVATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status related error.
        /// </summary>
        public static string EXCEPTION_TYPE_ORDER_STATUS_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ORDER_STATUS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status error.
        /// </summary>
        public static string EXCEPTION_TYPE_ORDER_STATUS_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_ORDER_STATUS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment related error.
        /// </summary>
        public static string EXCEPTION_TYPE_PAYMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PAYMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment error.
        /// </summary>
        public static string EXCEPTION_TYPE_PAYMENT_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PAYMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment request related error.
        /// </summary>
        public static string EXCEPTION_TYPE_PAYMENT_REQUEST_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PAYMENT_REQUEST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment request error.
        /// </summary>
        public static string EXCEPTION_TYPE_PAYMENT_REQUEST_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PAYMENT_REQUEST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points transaction related error.
        /// </summary>
        public static string EXCEPTION_TYPE_POINT_TRANSACTION_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_POINT_TRANSACTION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points transaction error.
        /// </summary>
        public static string EXCEPTION_TYPE_POINT_TRANSACTION_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_POINT_TRANSACTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product related error.
        /// </summary>
        public static string EXCEPTION_TYPE_PRODUCT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PRODUCT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product error.
        /// </summary>
        public static string EXCEPTION_TYPE_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider related error.
        /// </summary>
        public static string EXCEPTION_TYPE_PROVIDER_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PROVIDER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider error.
        /// </summary>
        public static string EXCEPTION_TYPE_PROVIDER_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_PROVIDER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control related error.
        /// </summary>
        public static string EXCEPTION_TYPE_REMOTE_CONTROL_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_REMOTE_CONTROL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control error.
        /// </summary>
        public static string EXCEPTION_TYPE_REMOTE_CONTROL_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_REMOTE_CONTROL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift related error.
        /// </summary>
        public static string EXCEPTION_TYPE_SHIFT_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_SHIFT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift error.
        /// </summary>
        public static string EXCEPTION_TYPE_SHIFT_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_SHIFT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock related error.
        /// </summary>
        public static string EXCEPTION_TYPE_STOCK_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_STOCK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock error.
        /// </summary>
        public static string EXCEPTION_TYPE_STOCK_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_STOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group related error.
        /// </summary>
        public static string EXCEPTION_TYPE_USER_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_USER_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group error.
        /// </summary>
        public static string EXCEPTION_TYPE_USER_GROUP_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_USER_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line related error.
        /// </summary>
        public static string EXCEPTION_TYPE_WAITING_LINE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_WAITING_LINE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line error.
        /// </summary>
        public static string EXCEPTION_TYPE_WAITING_LINE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_WAITING_LINE_NAME", resourceCulture);
            }
        }
    }
}
