using System.ComponentModel.DataAnnotations;
using Gizmo.Exceptions;

namespace Gizmo.Server.Exceptions;

/// <summary>
/// Achievement reward exception.
/// </summary>
[ExceptionFilterCode(ExceptionCode.AchievementReward)]
[Name("Achievement reward error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_ACHIEVEMENT_REWARD_NAME))]
[ExtendedDescription("Achievement reward related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_ACHIEVEMENT_REWARD_DESCRIPTION))]
public sealed class AchievementRewardException(AchievementRewardExceptionErrorCode errorCode) : ErrorCodeExceptionBase<AchievementRewardExceptionErrorCode>(errorCode)
{
}
