using System.ComponentModel.DataAnnotations;
using Gizmo.Exceptions;

namespace Gizmo.Server.Exceptions;

/// <summary>
/// Achievement exception.
/// </summary>
[ExceptionFilterCode(ExceptionCode.Achievement)]
[Name("Achievement error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_ACHIEVEMENT_NAME))]
[ExtendedDescription("Achievement related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_ACHIEVEMENT_DESCRIPTION))]
public sealed class AchievementException(AchievementExceptionErrorCode errorCode) : ErrorCodeExceptionBase<AchievementExceptionErrorCode>(errorCode)
{
}
