using Gizmo.Exceptions;
using System.ComponentModel.DataAnnotations;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Companion exception.
    /// </summary>
    /// <remarks>
    /// An exception used to communicate an error related to companion operation.
    /// </remarks>
    [ExceptionFilterCode(ExceptionCode.Companion)]
    [Name("Companion error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_COMPANION_NAME))]
    [ExtendedDescription("Companion related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_COMPANION_DESCRIPTION))]
    public sealed class CompanionException : ErrorCodeExceptionBase<CompanionExceptionErrorCode>
    {
        public CompanionException(string message, CompanionExceptionErrorCode errorCode, int? printerOrDriverErrorCode) : base(message, errorCode)
        {
            DeviceNativeErrorCode = printerOrDriverErrorCode;
        }

        public CompanionException(string message, CompanionExceptionErrorCode errorCode) : base(message, errorCode)
        {
        }

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        public CompanionException(CompanionExceptionErrorCode errorCode) : base(errorCode)
        { }

        /// <summary>
        /// Gets or sets optional device error code.
        /// </summary>
        public int? DeviceNativeErrorCode
        {
            get; set;
        }
    }
}
