using Gizmo.Exceptions;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Companion exception.
    /// </summary>
    /// <remarks>
    /// An exception used to communicate an error related to companion operation.
    /// </remarks>
    [Serializable()]
    [ExceptionFilterCode(ExceptionCode.Companion)]
    [Name("Companion error", nameof(Resources.Autogenerated.Resources.EXCEPTION_TYPE_COMPANION_NAME))]
    [ExtendedDescription("Companion related error", nameof(Resources.Autogenerated.Resources.EXCEPTION_TYPE_COMPANION_DESCRIPTION))]
    public class CompanionException : ErrorCodeExceptionBase<CompanionExceptionErrorCode>
    {
        public CompanionException(string message, CompanionExceptionErrorCode errorCode, int? printerOrDriverErrorCode) : base(message, errorCode)
        {
            DeviceNativeErrorCode = printerOrDriverErrorCode;
        }

        public CompanionException(string message, CompanionExceptionErrorCode errorCode) : base(message, errorCode)
        {
        }

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        public CompanionException(CompanionExceptionErrorCode errorCode) : base(errorCode)
        { }

        /// <summary>
        /// Serialization constructor.
        /// </summary>
        /// <param name="info">Serialization info.</param>
        /// <param name="context">Serialization context.</param>
        protected CompanionException(SerializationInfo info,
           StreamingContext context)
            : base(info, context)
        {
            if (info != null)
            {
                DeviceNativeErrorCode = (int?)info.GetValue(nameof(DeviceNativeErrorCode), typeof(int?));
            }
        }

        /// <summary>
        /// Gets or sets optional device error code.
        /// </summary>
        public int? DeviceNativeErrorCode
        {
            get; set;
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            base.GetObjectData(info, context);

            if (info != null)
            {
                info.AddValue(nameof(DeviceNativeErrorCode), DeviceNativeErrorCode);
            }
        }
    }
}
