using System.ComponentModel.DataAnnotations;
using Gizmo.Exceptions;

namespace Gizmo.Server.Exceptions
{
    [ExceptionFilterCode(ExceptionCode.InventoryException)]
    [Name("Inventory error", nameof(Resources.Autogenerated.Resources.EXCEPTION_TYPE_INVENTORY_NAME))]
    [ExtendedDescription("Inventory related error", nameof(Resources.Autogenerated.Resources.EXCEPTION_TYPE_INVENTORY_DESCRIPTION))]
    public sealed class InventoryException : ErrorCodeExceptionBase<InventoryExceptionErrorCode>
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Reservation error code.</param>
        public InventoryException(InventoryExceptionErrorCode errorCode) : base(errorCode)
        { }
    }
}
