using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Invoice payment exception.
    /// </summary>
    [Serializable()]
    [ExceptionFilterCode(ExceptionCode.InvoicePayment)]
    [Name("Invoice payment error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_INVOICE_PAYMENT_NAME))]
    [ExtendedDescription("Invoice payment related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_INVOICE_PAYMENT_DESCRIPTION))]
    public class InvoicePaymentExcpetion : PaymentExceptionBase<InvoicePaymentExceptionErrorCode>
    {
        #region CONSTRUCTOR

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        /// <param name="paymentMethodId">Payment method id.</param>
        public InvoicePaymentExcpetion(InvoicePaymentExceptionErrorCode errorCode, int paymentMethodId)
            : base(errorCode, paymentMethodId)
        { }

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        public InvoicePaymentExcpetion(InvoicePaymentExceptionErrorCode errorCode) : base(errorCode)
        { }

        /// <summary>
        /// Serialization constructor.
        /// </summary>
        /// <param name="info">Serialization info</param>
        /// <param name="context">Serialization context.</param>
        protected InvoicePaymentExcpetion(SerializationInfo info,
           StreamingContext context)
            : base(info, context)
        { }

        #endregion
    }
}
