using Gizmo.Exceptions;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Invoice exception.
    /// </summary>
    [Serializable()]
    [ExceptionFilterCode(ExceptionCode.Invoice)]
    [Name("Invoice error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_INVOICE_NAME))]
    [ExtendedDescription("Invoice related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_INVOICE_DESCRIPTION))]
    public class InvoiceException : ErrorCodeExceptionBase<InvoiceExceptionErrorCode>
    {
        #region CONSTRUCTOR

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        public InvoiceException(InvoiceExceptionErrorCode errorCode) : base(errorCode)
        {
        }

        /// <summary>
        /// Serialization constructor.
        /// </summary>
        /// <param name="info">Serialization info.</param>
        /// <param name="context">Serialization context.</param>
        protected InvoiceException(SerializationInfo info,
            StreamingContext context)
            : base(info, context)
        { }

        #endregion
    }
}
