using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// License reservation exception.
    /// </summary>
    [Serializable()]
    [Name("License reservation error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_LICENSE_RESERVATION_NAME))]
    [ExtendedDescription("License reservation related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_LICENSE_RESERVATION_DESCRIPTION))]
    public class LicenseResevationException : Exception
    {
        #region CONSTRUCTOR

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="message">Exception message.</param>
        public LicenseResevationException(string message)
            : base(message)
        { }


        /// <summary>
        /// Creates new instance.
        /// </summary>
        public LicenseResevationException() : base() { }

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="message">Exception message.</param>
        /// <param name="inner">Inner exception.</param>
        public LicenseResevationException(string message, Exception inner) : base(message, inner) { }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="info">Serialization info.</param>
        /// <param name="context">Serialization context.</param>
        protected LicenseResevationException(SerializationInfo info,
            StreamingContext context)
            : base(info, context) { }

        #endregion
    }
}
