using Gizmo.Exceptions;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Order status exception.
    /// </summary>
    [Serializable()]
    [ExceptionFilterCode(ExceptionCode.OrderStatus)]
    [Name("Order status error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_ORDER_STATUS_NAME))]
    [ExtendedDescription("Order status related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_ORDER_STATUS_DESCRIPTION))]
    public class OrderStatusException : ErrorCodeExceptionBase<OrderStatusExceptionErrorCode>
    {
        #region CONSTRUCTOR

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        public OrderStatusException(OrderStatusExceptionErrorCode errorCode) : base(errorCode)
        { }

        /// <summary>
        /// Serialization constructor.
        /// </summary>
        /// <param name="info">Serialization info.</param>
        /// <param name="context">Serialization context.</param>
        protected OrderStatusException(SerializationInfo info,
            StreamingContext context)
            : base(info, context)
        { }

        #endregion
    }
}
