using System.ComponentModel.DataAnnotations;
using Gizmo.Exceptions;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Payment request creation exception.
    /// </summary>
    [ExceptionFilterCode(ExceptionCode.PaymentRequest)]
    [Name("Payment request error", nameof(Resources.Autogenerated.Resources.EXCEPTION_TYPE_PAYMENT_REQUEST_NAME))]
    [ExtendedDescription("Payment request related error", nameof(Resources.Autogenerated.Resources.EXCEPTION_TYPE_PAYMENT_REQUEST_DESCRIPTION))]
    public sealed class PaymentRequestException : ErrorCodeExceptionBase<PaymentRequestExceptionErrorCode>
    {
        #region CONSTRUCTOR
        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="message">Error message.</param>
        /// <param name="errorCode">Error code.</param>
        public PaymentRequestException(string message, PaymentRequestExceptionErrorCode errorCode) : base(message, errorCode)
        {
        }
        #endregion
    }
}
