using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// Payment exception.
    /// </summary>
    [Serializable()]
    [ExceptionFilterCode(ExceptionCode.Payment)]
    [Name("Payment error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_PAYMENT_NAME))]
    [ExtendedDescription("Payment related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_PAYMENT_DESCRIPTION))]
    public class PaymentException : PaymentExceptionBase<PaymentExceptionErrorCode>
    {
        #region CONSTRUCTOR

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        /// <param name="paymentMethodId">Payment method id.</param>
        public PaymentException(PaymentExceptionErrorCode errorCode, int paymentMethodId) : base(errorCode, paymentMethodId)
        { }

        /// <summary>
        /// Serialization constructor.
        /// </summary>
        /// <param name="info">Serialization info.</param>
        /// <param name="context">Serialization context.</param>
        protected PaymentException(SerializationInfo info,
            StreamingContext context)
            : base(info, context)
        { }

        #endregion
    }
}
