using System.ComponentModel.DataAnnotations;
using Gizmo.Exceptions;

namespace Gizmo.Server.Exceptions
{
    /// <summary>
    /// User group exception.
    /// </summary>
    [ExceptionFilterCode(ExceptionCode.UserGroup)]
    [Name("User group error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_USER_GROUP_NAME))]
    [ExtendedDescription("User group related error", nameof(Shared.Resources.Autogenerated.Resources.EXCEPTION_TYPE_USER_GROUP_DESCRIPTION))]
    public class UserGroupException : ErrorCodeExceptionBase<UserGroupExceptionErrorCode>
    {
        #region CONSTRUCTOR

        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="errorCode">Error code.</param>
        public UserGroupException(UserGroupExceptionErrorCode errorCode) : base(errorCode)
        {
        }

        #endregion
    }
}
